---
- name: install dependencies for RHEL, Fedora & CentOS
  yum:
    name: "{{ directadmin_rhel_generic_packages }}"
    update_cache: yes
    state: present

- name: install everywhere but on CentOS7
  yum:
    name: "{{ directadmin_rhel_packages }}"
    update_cache: yes
    state: present
  when:
  - ansible_distribution not 'CentOS'
  - ansible_distribution_version is version(7, 'ne')

- name: install CentOS 7 specific requirements
  yum:
    name: "{{ directadmin_centos7_packages }}"
    update_cache: yes
    state: present
  when:
  - ansible_distribution is 'CentOS'
  - ansible_distribution_version is version(7, '=')

- name: install CentOS 8 specific requirements
  yum:
    name: "{{ directadmin_centos8_packages }}"
    update_cache: yes
    state: present
  when:
  - ansible_distribution is 'CentOS'
  - ansible_distribution_version is version(8, '=')