---
- name: Reconfigure redirect_host variable for DirectAdmin's webserver
  replace:
    path: "{{ directadmin_custombuild_path }}/options.conf"
    regexp: '^redirect_host\=server\.hostname\.com'
    replace: "redirect_host={{ directadmin_hostname }}"
  notify:
  - restart directadmin